#!/usr/bin/env bash
# Rebuild the assistant index and redeploy the Worker, using the Worker itself
# for embeddings (requires `wrangler login`; no API token needed).
#
# Usage: bash scripts/reindex-deploy.sh
set -euo pipefail
cd "$(dirname "$0")/.."

echo "==> 1/5 collecting chunks"
node scripts/build-index.mjs --dry-run

SECRET=$(openssl rand -hex 24)
export EMBED_SECRET="$SECRET"

echo "==> 2/5 deploying temporary embed endpoint"
python3 - "$SECRET" <<'PY'
import sys
secret = sys.argv[1]
p = 'worker/src/index.js'
s = open(p).read()
marker = '''    if (url.pathname !== "/api/chat" || request.method !== "POST")'''
temp = f'''    // TEMPORARY build-time endpoint: embed index chunks, gated by secret. Removed after index build.
    if (url.pathname === "/api/_embed" && request.method === "POST") {{
      if (request.headers.get("X-Embed-Secret") !== "{secret}") return json({{ error: "Not found" }}, 404, cors);
      const {{ texts }} = await request.json();
      const out = await env.AI.run("@cf/baai/bge-base-en-v1.5", {{ text: texts.slice(0, 25) }});
      return json({{ data: out.data }}, 200, cors);
    }}
'''
s = s.replace(marker, temp + marker, 1)
open(p, 'w').write(s)
PY
(cd worker && npx wrangler deploy >/dev/null 2>&1)

echo "==> 3/5 embedding chunks through the Worker"
node - <<'JS'
import("node:fs").then(async ({ writeFileSync }) => {
  const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
  const INDEX = (await import(process.cwd() + "/worker/src/index-data.js")).default;
  const texts = INDEX.chunks.map((c) => c.text);
  const vecs = [];
  for (let i = 0; i < texts.length; i += 25) {
    let res, tries = 0;
    for (;;) {
      res = await fetch("https://ask-rodrigo.rodrigosf672.workers.dev/api/_embed", {
        method: "POST",
        headers: { "Content-Type": "application/json", "X-Embed-Secret": process.env.EMBED_SECRET },
        body: JSON.stringify({ texts: texts.slice(i, i + 25) }),
      });
      if (res.ok) break;
      if (++tries > 10) throw new Error("embed failed " + res.status);
      await sleep(3000); // deploy propagation
    }
    vecs.push(...(await res.json()).data);
    console.log("    embedded", Math.min(i + 25, texts.length), "/", texts.length);
  }
  INDEX.chunks.forEach((c, k) => (c.vec = vecs[k].map((x) => Number(x.toFixed(6)))));
  writeFileSync("worker/src/index-data.js",
    "// GENERATED by scripts/build-index.mjs — do not edit by hand.\n// model: " + INDEX.model +
    " · chunks: " + INDEX.chunks.length + " · built: " + new Date().toISOString() +
    "\nexport default " + JSON.stringify(INDEX) + ";\n");
}).catch((e) => { console.error(e); process.exit(1); });
JS

echo "==> 4/5 removing temporary endpoint"
python3 - <<'PY'
import re
s = open('worker/src/index.js').read()
s = re.sub(r'    // TEMPORARY build-time endpoint.*?\n    \}\n', '', s, flags=re.S)
assert '_embed' not in s
open('worker/src/index.js', 'w').write(s)
PY

echo "==> 5/5 deploying final worker"
(cd worker && npx wrangler deploy 2>&1 | tail -1)
echo "done."
